# Generated by Django 6.0.3 on 2026-03-26 21:52

import firmware.models
import firmware.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('file', models.FileField(blank=True, storage=firmware.storage.FirmwareS3Storage, upload_to=firmware.models.firmware_upload_path)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('changelog', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
