# Generated by Django 6.0.3 on 2026-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwarerelease',
            name='device_type',
            field=models.CharField(blank=True, choices=[('arduino_nano_rp2040_connect', 'Arduino Nano RP2040 Connect'), ('esp32_2432s028', 'ESP32-2432S028 (CYD)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='firmwarerelease',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='firmwarerelease',
            unique_together={('version', 'device_type')},
        ),
    ]
