# Generated by Django 6.0.3 on 2026-03-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_updateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('arduino_nano_rp2040_connect', 'Arduino Nano RP2040 Connect'), ('esp32_2432s028', 'ESP32-2432S028 (CYD)')], max_length=30, null=True),
        ),
    ]
